#!/usr/bin/env python3

# Score for each round = score for selected shape + score for outcome
#
# Score for selected shape:
#
#   rock        = 1
#   paper       = 2
#   scissors    = 3
#
# Score for outcome:
#
#   defeat      = 0
#   draw        = 3
#   win         = 6
#
# Mapping (imagine these as rings, A < B < C < A < …, X < Y < Z < X < …):
#
#   0 1 2
#   -----
#   A B C : o (opponent)
#   X Y Z : y (you)
#
#     |   | Score for shape | Score for outcome
#   o | y | y + 1           | ((y - o + 1) % 3) * 3
#   --|---|-----------------|----------------------
#   0 | 0 | 1               | 3
#   0 | 1 | 2               | 6
#   0 | 2 | 3               | 0
#   1 | 0 | 1               | 0
#   1 | 1 | 2               | 3
#   … | … | …               | …
#
# Note: (y - o + 1) % 3 is
#
#   * 0 if your shape is "to the left" of opponent's shape,
#     e.f. opponent = rock (o=0), you = scissors (y=2)
#   * 1 for equal shapes (draw),
#   * 2 if your shape is "to the right" of opponent's shape,
#     e.g. opponent = rock (o=0), you = paper (y=1)…
#

import sys


VALUES = {
    "A": 0, "X": 0,
    "B": 1, "Y": 1,
    "C": 2, "Z": 2,
}


def score(lines):
    score = 0

    for line in lines:
        o, y = (VALUES[c] for c in line.split())
        score += (y + 1) + ((y - o + 1) % 3) * 3

    return score


if __name__ == '__main__':
    print(score(sys.stdin))
