#!/usr/bin/env python3

from itertools import chain
import sys


def crange(c1, c2):
    for c in range(ord(c1), ord(c2) + 1):
        yield chr(c)


TYPES = chain(crange('a', 'z'), crange('A', 'Z'))
PRIORITIES = {t: index for index, t in enumerate(TYPES, start=1)}


def halves(string):
    index = int(len(string) / 2)
    return string[:index], string[index:]


def compartments(string):
    return map(set, halves(string))


def intersect(first, *rest):
    return first.intersection(*rest)


def priority(item):
    return PRIORITIES[item]


if __name__ == '__main__':
    print(sum(sum(map(priority, intersect(*compartments(line)))) for line in sys.stdin))
