#!/usr/bin/env ruby

$LOAD_PATH << File.dirname($0)

load "solve-1"

class Simulation9001 < Simulation
  def move!(from, to, count)
    crates = from.pop(count)
    to.concat(crates)
  end
end

run(STDIN, Simulation9001) if __FILE__ == $0
