#!/usr/bin/env awk -f

# Sum up uninterrupted blocks of numbers.
#
# Set input record separator (RS) to split input between blocks separated by
# blank lines. Print the sum of all numbers within each block.

BEGIN { RS = "\n\n+" }
      { sum = 0; for (i = 1; i <= NF; i++) sum += $i; print sum }
