#!/usr/bin/env lua

dirname = string.match(arg[0], "(.*/)[^/]*")
local cpu = dofile(string.format("%s/cpu.lua", dirname))

local sum = 0

for _ in cpu:execute(io.stdin:lines()) do
  if cpu.cycle % 40 == 20 then
    sum = sum + (cpu.cycle * cpu.x)
  end
end

print(sum)
