#!/usr/bin/env python3

import os.path
import sys

sys.path.append(os.path.dirname(__file__))

from helpers import cmp, read

if __name__ == '__main__':
    results = (cmp(left, right) for left, right in read(sys.stdin))
    print(sum([i for i, x in enumerate(results, start=1) if x <= 0]))
